version: '3.1'

services:

  postgresdb:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=vas
      - POSTGRES_DB=mydb
    networks:
      - foodrecepies_net

  backend:
    image: backend:v0.1
    build: 
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/opt/backend
    depends_on:
      - postgresdb
    networks:
      - foodrecepies_net

  frontend:
    image: frontend:v0.1
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 8080:5000
    volumes:
      - ./frontend:/opt/frontend
    environment:
      BACKEND_URL: http://localhost:5000
    networks:
      - foodrecepies_net

networks:
  foodrecepies_net:
    driver: bridge  
