FROM python:3

RUN mkdir -p /opt/frontend
WORKDIR  /opt/frontend

COPY frontend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
# COPY frontend/*.py ./ 
ADD frontend/ ./

CMD ["python", "app.py"]